version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d  # 初期化スクリプトをマウント

  backend:
    build: ./backend
    container_name: go_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
      GO_ENV: "development"
    volumes:
      - ./backend:/app:cached  # :cachedを追加
      # - ./backend:/app
      # - ./backend/tmp:/app/tmp  # air用の一時ディレクトリ
    tty: true
    command: sh -c 'go mod tidy && air'

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"  # 3000から5173に変更
    volumes:
      - ./frontend:/app
      - /app/node_modules  # node_modules のキャッシュを防ぐ
    environment:
      - CHOKIDAR_USEPOLLING=true  # ファイル変更を確実に検知させる
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  postgres-data:
